### ISSUE TITLE
Awilix 7.x

### ISSUE THREAD

**Issue by davidzwa** [jeffijoe/awilix-express#42]
Hi there, congrats with the new major on `awilix`!

Would love to upgrade `awilix` with `awilix-express` etc. Thanks in advance for your awesome work 🥳

**Comment by jeffijoe** [comment]
Oops, I forgot 😅 

Done now, v7 is out.

**Comment by davidzwa** [comment]
Awesome job! Did you know, a bot like renovate and whitesource can trigger PR's for this automagically.
Really helps me out so far.

https://github.com/fdm-monster/fdm-monster/blob/develop/renovate.json
I can help you set it up if you want

**Comment by jeffijoe** [comment]
I don't have automatic releases for `awilix-express` and I am also not sure if its possible to make sure that the `awilix-express` package follows the same major version as `awilix`?

**Comment by jeffijoe** [comment]
The human would be the person hitting the merge button, so would have to set it up to not auto-merge.

I think I'll hold off on this for now. I would have found out eventually myself once upgrading my own projects failed due to the missing update on the `awilix-koa` side. Thanks though!

**Comment by davidzwa** [comment]
No problem, I will ping you with a PR/issue as I've done before if that's no problem.
