### ISSUE TITLE
Awilix 8.0 peerDependency

### ISSUE THREAD

**Issue by davidzwa** [jeffijoe/awilix-express#45]
Thanks for keeping Awilix awesome!

https://github.com/jeffijoe/awilix-express/blob/4beb6d4136faf7cffe7131bdfe271176f7b46f26/package.json#L63
Could you be so kind to update or loosen the peerDep?

**Comment by jeffijoe** [comment]
Done. I removed the peer deps, too. so this shouldn't be a problem anymore.
